### ISSUE TITLE
访问ipv6资源失败

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/light-server#1]
![img_2016-11-12 17 44 29](https://cloud.githubusercontent.com/assets/5450996/20236926/b75b2fbe-a8ff-11e6-9f81-94ae4b2dad1a.jpg)

reported by @zhsj

**Comment by gaoyifan** [comment]
fixed in 5aae3359b08e98afd3d1880076972938c15654a6

**Comment by zzh1996** [comment]
我试了一下，仍然不可以：
```
错误

您所请求的网址（URL）无法获取

当尝试取回该 URL 时遇到下面的错误：http://bt.neu6.edu.cn/

连接到 2001:da8:9000::232 失败。

系统返回以下内容：(101) Network unreachable

The remote host or network may be down. Please try the request again.

缓存服务器的管理员 webmaster.


已由 1a89a9ff1d13 (squid/3.5.20) 生成 Sat, 26 Nov 2016 11:24:10 GMT
```

**Comment by gaoyifan** [comment]
目前LUGI没有分配ipv6地址，网关也没有ipv6路由。如果要让light支持ipv6，需要先对内网架构进行升级。
5aae335 只是优先使用ipv4访问。
