### ISSUE TITLE
访问被拒绝

### ISSUE THREAD

**Issue by zzh1996** [ustclug/light-server#5]
```
当尝试取回该 URL 时遇到下面的错误：http://202.38.79.49:8888/login.php

访问被拒绝。
```

**Comment by gaoyifan** [comment]
https://github.com/ustclug/light-server/blob/master/.docker/rootfs/etc/squid/squid.conf#L9

**Comment by gaoyifan** [comment]
更新PAC：非标准端口走本地
https://github.com/ustclug/light-list/commit/33b1582fcd81aa65b848165c2f7308dc232560c8
